#!/bin/bash
function factorial {
    if [[ $1 -eq 0 ]]
    then
        echo 1
    else
        local result=$(factorial $(($1 - 1)))
        echo $(($result * $1))
    fi
}
echo "Enter a number:"
read number
factorial_result=$(factorial $number)
echo "The factorial of $number is $factorial_result"
